run:
  go: "1.24.2"
  tests: false

output:
  # Make output more digestible with quickfix in vim/emacs/etc.
  sort-results: true
  print-issued-lines: false

linters:
  enable:
    - nolintlint
    - revive
    - staticcheck
    - asasalint
    - bodyclose
    - contextcheck
    - cyclop
    - dupword
    - errname
    - gosec
    - nakedret
    - exhaustive
    - loggercheck
    - misspell
    - nestif
    - perfsprint
    - prealloc
    - predeclared
    - testifylint
    - usestdlibvars
    - tparallel
    - unconvert
    - unparam
    - wsl

formatters:
  enable:
    - gofumpt
    - goimports

linters-settings:
  govet:
    # These govet checks are disabled by default, but they're useful.
    enable:
      - nilness
      - reflectvaluecompare
      - sortslice
      - unusedwrite
      - defers
      - atomic
      - nilfunc
      - printf
      - sortslice
      - tests
