# This file was generated by GoReleaser. DO NOT EDIT.
cask "frens" do
  desc "A friendship management & journaling application for introverts and not only."
  homepage "https://github.com/roma-glushko/frens"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frens"

  on_macos do
    on_intel do
      url "https://github.com/roma-glushko/frens/releases/download/v0.0.8/frens_v0.0.8_darwin_amd64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "70329d3e6424a481da9e71b3b6dbc7f123bebebf5e3d1539b52199521f5152b2"
    end
    on_arm do
      url "https://github.com/roma-glushko/frens/releases/download/v0.0.8/frens_v0.0.8_darwin_arm64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "4bed6fd841ca2bffc990c9131b933f279773fea48b2542df0fbac04e3db6a8ff"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/roma-glushko/frens/releases/download/v0.0.8/frens_v0.0.8_linux_amd64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "2b0e7afdd44544017f5aa3726a82fbe3af54422df44a180e1d12b0add9a52360"
    end
    on_arm do
      url "https://github.com/roma-glushko/frens/releases/download/v0.0.8/frens_v0.0.8_linux_arm64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "c390ef1e938d4d93a351e92be07eb13d732eca2b188427033d29c0a56c5f12a8"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/frens"]
    end
  end

  caveats do
    "frens --help"
  end

  # No zap stanza required
end
