# This file was generated by GoReleaser. DO NOT EDIT.
cask "frens" do
  desc "A friendship management & journaling application for introverts and not only."
  homepage "https://github.com/roma-glushko/frens"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frens"

  on_macos do
    on_intel do
      url "https://github.mycompany.com/roma-glushko/frens/releases/download/v0.0.2/frens_v0.0.2_darwin_amd64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "da9d24ee36757d10894c3a351f2163d5f5a540904893f0a44224eb7775dfc6ab"
    end
    on_arm do
      url "https://github.mycompany.com/roma-glushko/frens/releases/download/v0.0.2/frens_v0.0.2_darwin_arm64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "2be7f8ed4c8cc406ce55afe426282f8115646ad71b68acde0b9cf133505e2913"
    end
  end

  on_linux do
    on_intel do
      url "https://github.mycompany.com/roma-glushko/frens/releases/download/v0.0.2/frens_v0.0.2_linux_amd64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "bc90e8a19537375d92ffc380de822251c61925b9a02b845bd080c3c6a7d71d6b"
    end
    on_arm do
      url "https://github.mycompany.com/roma-glushko/frens/releases/download/v0.0.2/frens_v0.0.2_linux_arm64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "858d7da6e0d99276480b095a8cda71db0e5731f0121c59403bb43f77a3593a75"
    end
  end

  caveats do
    "frens --help"
  end

  # No zap stanza required
end
