# This file was generated by GoReleaser. DO NOT EDIT.
cask "frens" do
  desc "A friendship management & journaling application for introverts and not only."
  homepage "https://github.com/roma-glushko/frens"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "frens"

  on_macos do
    on_intel do
      url "https://github.com/roma-glushko/frens/releases/download/v0.0.3/frens_v0.0.3_darwin_amd64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "3619167cae30ce79a8c2f950ac038ca3707eedc04acf0adbd0e67aaf1d5fc5b3"
    end
    on_arm do
      url "https://github.com/roma-glushko/frens/releases/download/v0.0.3/frens_v0.0.3_darwin_arm64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "240bf4b54890d9d8a37e6fa86729716ca145b267562e424e730d06cc3b57cb61"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/roma-glushko/frens/releases/download/v0.0.3/frens_v0.0.3_linux_amd64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "83c7f1586cd73346bda26a1ff04ed508ace297079ea285caaee527e9d90a47e8"
    end
    on_arm do
      url "https://github.com/roma-glushko/frens/releases/download/v0.0.3/frens_v0.0.3_linux_arm64.tar.gz",
        verified: "github.com/roma-glushko/frens/",
        using: :homebrew_curl,
        user_agent: "Homebrew/1.0 (macOS)"
      sha256 "67f77dd37154575aa3221c358377d2258f7b53f92346238a1e26b3e33679c949"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/frens"]
    end
  end

  caveats do
    "frens --help"
  end

  # No zap stanza required
end
