name: Tests

concurrency:
  group: tests-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Testing

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Cache Go tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/.local/go/bin
            ~/go/pkg/mod
          key: go-tools-${{ runner.os }}-${{ hashFiles('Makefile') }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-cache-${{ runner.os }}-

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: make test-ci

      - name: Get Cover
        if: github.event_name == 'pull_request'
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}